import { AgentSkill } from "../../harness/index.ts";

export const CreateStudyArtifactsSkill = AgentSkill.make({
  name: "create-study-artifacts",
  description: "Crear y gestionar artefactos de estudio: notas en markdown, quizzes, tests, entregas e intentos corregidos.",
  content: [
    "# Crear artefactos de estudio",
    "",
    "Usa esta skill cuando el estudiante te pida crear notas de estudio, quizzes, tests o entregas de práctica.",
    "",
    "Los artefactos son objetos de estudio que se guardan:",
    "- `note`: título más contenido markdown. Las notas no se entregan ni se corrigen.",
    "- `quiz`: título más preguntas de opción múltiple o verdadero/falso, corregibles automáticamente.",
    "- `test`: título más preguntas. Puede incluir opción múltiple, verdadero/falso y respuesta corta.",
    "",
    "Comandos disponibles:",
    "- `artifacts list [note|quiz|test]`: lista los artefactos guardados.",
    "- `artifacts show <artifactId>`: muestra el JSON de un artefacto.",
    "- `artifacts create '<json>'`: create a note, quiz, or test from CreateArtifactInput JSON. Always wrap JSON in single quotes.",
    "- `artifacts submit '<json>'`: submit answers for a quiz or test from SubmitAttemptInput JSON. Always wrap JSON in single quotes.",
    "- `artifacts attempts [artifactId]`: list attempts.",
    "- `artifacts grade <attemptId>`: grade and persist a submitted attempt.",
    "",
    "CreateArtifactInput examples:",
    "- `artifacts create '{\"kind\":\"note\",\"title\":\"Derivatives summary\",\"markdown\":\"# Derivatives\\n...\"}'`",
    "- `artifacts create '{\"kind\":\"quiz\",\"title\":\"Basics quiz\",\"questions\":[{\"type\":\"true-false\",\"id\":\"q1\",\"prompt\":\"2+2=4\",\"correctAnswer\":true,\"explanation\":\"Basic arithmetic.\"}]}'`",
    "- `artifacts create '{\"kind\":\"quiz\",\"title\":\"Concept quiz\",\"questions\":[{\"type\":\"multiple-choice\",\"id\":\"q1\",\"prompt\":\"Which option is qualitative?\",\"options\":[{\"id\":\"qualitative\",\"text\":\"Qualitative\"},{\"id\":\"quantitative\",\"text\":\"Quantitative\"}],\"correctOptionId\":\"qualitative\",\"explanation\":\"Qualitative data describes qualities.\"}]}'`",
    "",
    "Comillas dentro del JSON:",
    "- El argumento va envuelto en comillas simples. Las comillas simples que aparezcan",
    "  DENTRO del JSON no se escapan: escribe `<class 'int'>`, nunca `<class \\'int\\'>`.",
    "  JSON no admite el escape de la comilla simple y el comando fallará.",
    "- Las comillas dobles dentro de una cadena JSON sí se escapan, como siempre: `\\\"`.",
    "",
    "Fórmulas dentro del artefacto:",
    "- Las matemáticas van en LaTeX igual que en el chat: $ ... $ dentro de una frase,",
    "  $$ ... $$ para una fórmula sola. Vale en enunciados, opciones y explicaciones.",
    "- Prefiere la notación que no necesita barra invertida, que es casi toda la que",
    "  hace falta: $A^T A$, $(A^T A)^{-1}$, $R^2$, $x_i$.",
    "- Si necesitas un comando con barra invertida, escríbela DOBLE, porque el texto viaja",
    "  dentro de un JSON.",
    "",
    "Reglas de las preguntas de opción múltiple:",
    "- `options` deben ser objetos, no cadenas: `{\"id\":\"a\",\"text\":\"Texto de la opción\"}`.",
    "- `correctOptionId` debe coincidir exactamente con el `id` de una opción.",
    "",
    "SubmitAttemptInput example:",
    "- `artifacts submit '{\"artifactKind\":\"quiz\",\"artifactId\":\"<id>\",\"answers\":[{\"questionType\":\"true-false\",\"questionId\":\"q1\",\"answer\":true}]}'`",
    "",
    "## Qué pasa con un artefacto después de crearlo",
    "",
    "Los artefactos NO son texto de chat. Aparecen en el panel del estudiante, donde los",
    "abre, los responde y se corrigen solos con explicación por pregunta.",
    "",
    "Por eso, cuando crees uno:",
    "- Dilo en una frase y remite a su panel de estudio, sin describir dónde está en",
    "  la pantalla: la interfaz puede cambiar. Ejemplo: \"Listo, tienes el quiz de redes",
    "  en tu panel de estudio.\"",
    "- **No repitas las preguntas en el chat.** Ya las tiene delante, y duplicarlas le",
    "  hace responder en el sitio equivocado.",
    "- **No le pidas que conteste por chat** ni le propongas un formato tipo \"q1: b\".",
    "  Perdería la corrección automática y el registro de su progreso.",
    "- **No enseñes el id del artefacto.** Es un detalle interno.",
    "- Ofrece lo que sí aporta: resolver dudas mientras lo hace, o repasar después.",
    "",
    "Flujo de trabajo:",
    "1. Si el artefacto se basa en materiales subidos, consulta primero el material.",
    "2. Crea un artefacto compacto que responda exactamente a lo pedido.",
    "3. Usa ids de pregunta estables como `q1`, `q2`, `q3`.",
    "4. En los quizzes prefiere verdadero/falso y opción múltiple, porque la corrección es determinista.",
    "5. Cuando el estudiante entregue respuestas, guarda el intento y después corrígelo.",
    "6. Redacta títulos, enunciados y explicaciones en el idioma del estudiante (por defecto, español)."
  ].join("\n")
});
