import { AgentSkill } from "../../harness/index.ts";

export const DebateWithTheStudentSkill = AgentSkill.make({
  name: "debate-with-the-student",
  description: "Poner a prueba al estudiante discutiendo con él sobre un tema, sin nota ni corrección, para ver hasta dónde entiende de verdad.",
  content: [
    "# Debatir con el estudiante",
    "",
    "Usa esta skill cuando el estudiante quiera debatir, discutir un tema, o pida que le",
    "pongas a prueba o que compruebes si de verdad lo entiende.",
    "",
    "## Para qué sirve",
    "",
    "Un quiz mide si acierta la respuesta. Un debate mide si entiende el porqué, que es",
    "lo que separa haber memorizado de haber comprendido. Además revela lagunas que una",
    "pregunta cerrada no toca: en cuanto tiene que defender una idea con sus palabras, se",
    "ve dónde se apoya en una regla aprendida de memoria.",
    "",
    "## Cómo se debate",
    "",
    "1. Elige un tema del material o de lo que esté estudiando y toma una postura.",
    "2. Pide que justifique lo que afirma. \"¿Por qué?\" es tu pregunta principal.",
    "3. Rebate con argumentos, nunca con autoridad. Nada de \"porque lo dice el libro\".",
    "4. Aprieta donde flojee, pero un paso cada vez. No amontones tres objeciones.",
    "5. Si te da un argumento bueno, **concédelo y dilo**. Reconocer que tiene razón es",
    "   parte del ejercicio, y además es lo honesto.",
    "",
    "## Reglas que no se rompen",
    "",
    "- **Sin nota y sin corrección.** No puntúas, no dices \"incorrecto\", no llevas la",
    "   cuenta de aciertos. Aquí se piensa en voz alta, y para eso hace falta poder",
    "   equivocarse sin coste.",
    "- **Abogado del diablo, no mentiroso.** Puedes defender la postura contraria para",
    "   hacerle pensar, pero deja claro que estás haciendo de abogado del diablo. Nunca",
    "   presentes algo falso como si fuera cierto: si el tema tiene una respuesta",
    "   establecida y él la acierta, concédela en lugar de seguir tirando del hilo.",
    "- **Antes de terminar, deshaz el nudo.** Si has defendido una postura falsa como",
    "   ejercicio, cierra el debate dejando claro cuál es la respuesta buena. El",
    "   estudiante no se puede ir del debate con una idea equivocada en la cabeza.",
    "- **Al tema, no a la persona.** Discutes ideas, no lo listo que es.",
    "",
    "## Al terminar",
    "",
    "Cuando el estudiante lo deje o pida terminar:",
    "",
    "1. Resume en pocas líneas qué ha demostrado entender y qué se ha quedado flojo.",
    "2. Guarda lo aprendido en la memoria con `profile remember`: lo que ha defendido",
    "   bien como `strength`, lo que no ha sabido sostener como `gap`. Usa el tema como",
    "   `topic` y una frase concreta como `detail`.",
    "3. Ofrece un siguiente paso: repasar el punto flojo o un quiz sobre él.",
    "",
    "Ejemplo de lo que se guarda tras un debate:",
    '`profile remember \'[{"kind":"strength","topic":"TCP","detail":"explica bien por qué el handshake evita conexiones falsas"},{"kind":"gap","topic":"TCP","detail":"no sabe justificar cuándo conviene UDP frente a TCP"}]\'`'
  ].join("\n")
});
