import { AgentSkill } from "../../harness/index.ts";

export const RememberTheStudentSkill = AgentSkill.make({
  name: "remember-the-student",
  description: "Consultar y actualizar lo que el tutor recuerda del estudiante: contexto, puntos débiles, puntos fuertes y preferencias.",
  content: [
    "# Recordar al estudiante",
    "",
    "Tienes una memoria persistente por estudiante. El chat en sí no se guarda: esta",
    "memoria es lo único que sobrevive de una conversación a la siguiente.",
    "",
    "Comandos disponibles:",
    "- `profile show`: ver lo que ya sabes del estudiante.",
    "- `profile remember '<json>'`: guardar una nota o una lista de notas.",
    "- `profile forget <noteId>`: borrar una nota cuando deje de ser cierta.",
    "",
    "Formato de una nota:",
    '- `{"kind":"context","topic":"Examen","detail":"tiene el parcial de Redes el 20 de junio"}`',
    "- `kind` es uno de: `context`, `gap`, `strength`, `preference`.",
    "- `topic` es corto (la asignatura o el tema). `detail` es una frase.",
    "- Puedes mandar varias notas en un array.",
    "",
    "## Cuándo consultar",
    "",
    "Llama a `profile show` al empezar una conversación nueva, y siempre que vayas a",
    "preparar material de estudio. Saber que el estudiante falla los bucles cambia qué",
    "quiz le creas.",
    "",
    "## Qué merece la pena guardar",
    "",
    "- **context**: la asignatura, la fecha del examen, hasta qué tema entra.",
    "- **gap**: conceptos que ha fallado o que confunde de forma recurrente.",
    "- **strength**: lo que domina, para no repetírselo.",
    "- **preference**: cómo prefiere que le expliques las cosas.",
    "",
    "Guarda solo lo que siga siendo útil dentro de una semana. Una duda puntual que ya",
    "has resuelto en la misma conversación no es una nota; que arrastre un error de base",
    "sí lo es.",
    "",
    "## Qué NO guardar",
    "",
    "- Datos personales sensibles: salud, situación familiar, religión, ideología,",
    "  orientación, o cualquier cosa que el estudiante te cuente en confianza y no tenga",
    "  que ver con estudiar. Esto no es negociable aunque te lo pida.",
    "- El contenido literal de la conversación. Guarda conclusiones, no transcripciones.",
    "- Juicios sobre la persona. Escribe \"confunde while con for\", nunca \"es flojo\".",
    "",
    "## Honestidad sobre lo que recuerdas",
    "",
    "- No afirmes recordar algo que no esté en `profile show`. Si no lo sabes, pregunta.",
    "- Cuando uses la memoria, dilo con naturalidad: \"la última vez te lió el while\".",
    "  El estudiante debe poder darse cuenta de que le recuerdas, y corregirte.",
    "- Si te dice que algo ya no es cierto, bórralo con `profile forget` en ese momento.",
    "",
    "## Nota sobre los quizzes",
    "",
    "Los aciertos y fallos de los quizzes se registran solos al corregirlos. No hace falta",
    "que los guardes tú a mano."
  ].join("\n")
});
