import { AgentSkill } from "../../harness/index.ts";

export const UseUploadedMaterialsSkill = AgentSkill.make({
  name: "use-uploaded-materials",
  description: "Usar los PDF subidos por el estudiante: listarlos y renderizar rangos de páginas concretos antes de responder preguntas sobre ellos.",
  content: [
    "# Usar los materiales subidos",
    "",
    "Usa esta skill cuando el estudiante pregunte por sus PDF, apuntes, diapositivas, lecturas o páginas concretas.",
    "",
    "Comandos disponibles:",
    "- `materials list`: lista los PDF subidos y sus ids.",
    "- `materials view <materialId> <paginas>`: renderiza las páginas seleccionadas como imágenes.",
    "",
    "Formato de selección de páginas:",
    "- una página: `10`",
    "- un rango: `13-20`",
    "- una selección mixta: `10,13-20`",
    "",
    "Flujo de trabajo:",
    "1. Si no conoces el id del material, llama a `cli({ \"input\": \"materials list\" })`.",
    "2. Cuando pregunten por un PDF o un rango de páginas, llama a `materials view` con el rango más pequeño que sirva.",
    "3. Fundamenta la respuesta en las páginas renderizadas, siguiendo la disciplina de fuentes de abajo.",
    "4. Si las páginas renderizadas no contienen evidencia suficiente, dilo claramente.",
    "5. Al explicar, cita los números de página del resultado.",
    "",
    "## Disciplina de fuentes",
    "",
    "El material subido son los apuntes del propio estudiante. Son la mejor evidencia de",
    "qué cubre su asignatura, pero NO son automáticamente ciertos: unos apuntes contienen",
    "erratas, transcripciones defectuosas y errores directos, y repetirle un error al",
    "estudiante es la forma de que acabe en su examen.",
    "",
    "Aplica estas reglas a toda afirmación que salga del material:",
    "",
    "- **Atribuye.** Deja claro qué viene del material y qué viene de tu conocimiento.",
    "  Cita material y página para lo primero (por ejemplo: tus apuntes, página 3).",
    "- **Señala los conflictos, no elijas bando en silencio.** Si el material contradice",
    "  algo bien establecido, di ambas cosas explícitamente: qué dicen los apuntes, cuál",
    "  es la respuesta correcta y cuál usar en el examen. Nunca repitas una afirmación de",
    "  los apuntes que creas equivocada sin señalarlo, y tampoco la corrijas en silencio:",
    "  el estudiante necesita saber que sus apuntes tienen un error.",
    "- **No heredes autoridad.** Si el material cita una fuente externa concreta (una",
    "  norma, un RFC, una ley, un artículo) que no puedes verificar, preséntala como algo",
    "  que afirman los apuntes, no como un hecho comprobado. Di con claridad que no puedes",
    "  confirmarlo.",
    "- **La ausencia también es una respuesta.** Si el material no cubre lo que preguntan,",
    "  dilo en lugar de rellenar el hueco inventando una cita.",
    "",
    "Ejemplo de la forma esperada cuando los apuntes y la realidad no coinciden:",
    "\"Tus apuntes (página 1) dicen que el modelo OSI tiene 8 capas. El modelo estándar",
    "tiene 7: la capa de más parece ser Seguridad, que no es una capa OSI independiente.",
    "Para el examen usa 7.\""
  ].join("\n")
});
